
 <!--
         
    gn_NavMenu("prod_info", "Processors|/hardwaredesign/processors.htm?iid=hdnav_dhtml+comp_proc&", "Motherboards|/design/motherbd/index.htm?iid=hdnav_dhtml+comp_mboards&", "Chipsets|/design/chipsets/index.htm?iid=hdnav_dhtml+comp_chipsets&",  "Intel&#174; Platform Memory|/technology/memory/index.htm?iid=hdnav_dhtml+comp_mem&", "Notebook Components|/design/mobile/index.htm?iid=hdnav_dhtml+comp_notebooks&", "Server Components & Products|/design/servers/buildingblocks/index.htm?iid=hdnav_dhtml+comp_servers&",  "Networking & Communications Design Components|/design/network/index.htm?iid=hdnav_dhtml+comp_netcom&", "Handheld & Handset Components|/design/wireless/wireless.htm?iid=hdnav_dhtml+comp_handsets&", "Intel&#174; Flash Memory|/design/flash/index.htm?iid=hdnav_dhtml+comp_flash&", "Embedded Components|/design/shared/embedded/index.htm?iid=hdnav_dhtml+comp_emb&", "Consumer Electronics Components & Designs|/design/celect/index.htm?iid=hdnav_dhtml+comp_ce&", "Storage Products|http://intel.com/products/server/storage/bb.htm?iid=hdnav_dhtml+comp_storage&", "Intel&#174; Software Development Products|/software/products/index.htm?iid=hdnav_dhtml+comp_softdev&");   
    //gn_NavMenu("design_sol", "Processors|processors.htm", "Chipsets|NEED_URL");   
    //gn_NavMenu("dev_programs", "Networking & Communications|!", "Intel&#174; Converged Communications Developer Program|http://intel.com/network/csp/programs/ccd/8295web.htm", "Intel&#174; Communications Alliance|/design/network/ica/", "Intel&#174;  Modular Communications Platforms Early Access Program|http://cedar.intel.com/cgi-bin/ids.dll/content/content.jsp?cntKey=Generic+Editorial::eap_mcp_main&cntType=IDS_EDITORIAL&catCode=DDQ", "PCI Express Architecture in Communications|/technology/pciexpress/devnet/comms.htm", "Wireless/Handhelds|!", "Intel&#174; Personal Internet Client Architecture (Intel PCA) Developer Network|/pca/", "Desktop PC|!", "Intel&#174; Developer Network for Digital Home Developer Network|/technology/dhdevnet/", "Intel&#174; Innovative PC Program|/technology/easeofuse/innovpc/", "Intel&#174; Developer Network for PCI Express Architecture in Desktop|/technology/pciexpress/devnet/desktop.htm");   
    //gn_NavMenu("tools_down", "Design Tools|tnd.htm#1|", "Drivers, BIOS & support Software|tnd.htm#2|", "Selector Tools|tnd.htm#4|", "Intel&#174; Evaluation Software|/software/products/global/eval.htm|");   
    //gn_NavMenu("tech_trends", "Rearch & Development at Intel|http://intel.com/labs/", "Research at Intel|http://intel.com/research/", "Digital Home Initiative|/technology/digitalhome/", "Intel&#174; Wireless Technologies|/design/pca/technologies/", "Intel&#174; Server Technologies|/design/servers/technologies/", "Intel&#174; XScale&#153; Technology|/communications/xscale.htm", "Embedded Technologies & Initiatives|/technology/embedded/", "Ultra-Wideband Technology (UWB)|/technology/ultrawideband/");
	//gn_NavMenu("events_pubs", "Events|!", "Intel&#174; Developer Forum (IDF)|/idf/", "Training|!", "Intel&#174; Software College|https://shale.intel.com/softwarecollege/", "Software Training & Tutorials|http://cedar.intel.com/cgi-bin/ids.dll/topic.jsp?catCode=BKK&BV_UseBVCookie=no", "Intel Networking & Communications Training|http://intel.com/netcomms/events/telecom.htm", "Communications e-Seminar Series |http://seminar2.techonline.com/~intel22/ws2003/", "Telecom Educational Services|http://intel.com/network/csp/resources/news_events/edu/", "Intel&#174; Interactive Learning Solutions|/platforms/applied/studentstation/", "Publications|!", "Intel&#174; Press Technical Books|/intelpress/", "Intel&#174;Technology Journal|/technology/itj/", "Technology@Intel Magazine|/update/");   
   
   
  //-->
